### ISSUE TITLE
Configure mkdocs

### ISSUE THREAD

**Issue by Berupor** [Berupor/Calendar-Analytics#20]
Branch: https://github.com/Berupor/Calendar-Analytics/tree/dev_5.0.0

I have completed the development of the new version 5.0 of the project. However, I am unable to release it due to issues with the documentation. Specifically, I am encountering errors with mkdocstrings. I have attempted to resolve the problem by using both the crystal and legacy engines. Unfortunately, I encountered the following error during the process:

```console
    self._proc = subprocess.Popen(command, stdout=subprocess.PIPE)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1022, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1899, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'crystal'
```

It seems that the 'crystal' executable is not found, resulting in this FileNotFoundError.

**Comment by pawamoy** [comment]
Hello, your project is written in Python right, not Crystal?

When you install mkdocstrings, try installing it with this: `pip install 'mkdocstrings[python]'`.
